import * as TYPES from "../types"

export const BOSS_MOCK = [
  {
    id: 73,
    name: "Tentacruel",
    type: [TYPES.WATER, TYPES.POISON],
    level: 41,
    baseAttack: 166,
    baseDefense: 209,
    baseStamina: 2025,
    individualAttack: 15,
    individualDefense: 15,
    individualStamina: 0,
    moves: {
      quick: 4,
      charged: 10,
    },
  },
  {
    id: 196,
    name: "Mentali",
    type: [TYPES.PSYCHIC],
    level: 41,
    baseAttack: 261,
    baseDefense: 175,
    baseStamina: 3000,
    individualAttack: 15,
    individualDefense: 15,
    individualStamina: 0,
    moves: {
      quick: 5,
      charged: 12,
    },
  },
  {
    id: 248,
    name: "Tyranocif",
    type: [TYPES.DARK, TYPES.ROCK],
    level: 41,
    baseAttack: 251,
    baseDefense: 207,
    baseStamina: 9000,
    individualAttack: 15,
    individualDefense: 15,
    individualStamina: 0,
    moves: {
      quick: 6,
      charged: 13,
    },
  },
  {
    id: 384,
    name: "Rayquaza",
    type: [TYPES.DRAGON, TYPES.FLYING],
    level: 41,
    baseAttack: 284,
    baseDefense: 170,
    baseStamina: 12500,
    individualAttack: 15,
    individualDefense: 15,
    individualStamina: 0,
    moves: {
      quick: 7,
      charged: 11,
    },
  },
  {
    id: 150,
    name: "MewTwo",
    type: [TYPES.PSYCHIC],
    level: 41,
    baseAttack: 300,
    baseDefense: 182,
    baseStamina: 22500,
    individualAttack: 15,
    individualDefense: 15,
    individualStamina: 0,
    moves: {
      quick: 5,
      charged: 14,
    },
  },
]
