import * as TYPES from "../types"

export const POKEMON_MOCK = [
  {
    id: 68,
    name: "Mackogneur",
    type: [TYPES.FIGHTING],
    level: 40,
    baseAttack: 234,
    baseDefense: 159,
    baseStamina: 207,
    individualAttack: 15,
    individualDefense: 15,
    individualStamina: 15,
    moves: {
      quick: 1,
      charged: 2,
    },
  },
  {
    id: 297,
    name: "Hariyama",
    type: [TYPES.FIGHTING],
    level: 40,
    baseAttack: 209,
    baseDefense: 114,
    baseStamina: 302,
    individualAttack: 15,
    individualDefense: 15,
    individualStamina: 15,
    moves: {
      quick: 1,
      charged: 2,
    },
  },
  {
    id: 149,
    name: "Dracolosse",
    type: [TYPES.DRAGON, TYPES.FLYING],
    level: 29,
    baseAttack: 263,
    baseDefense: 198,
    baseStamina: 209,
    individualAttack: 15,
    individualDefense: 12,
    individualStamina: 11,
    moves: {
      quick: 3,
      charged: 4,
    },
  },
  {
    id: 134,
    name: "Aquali",
    type: [TYPES.WATER],
    level: 28,
    baseAttack: 205,
    baseDefense: 161,
    baseStamina: 277,
    individualAttack: 14,
    individualDefense: 11,
    individualStamina: 9,
    moves: {
      quick: 5,
      charged: 6,
    },
  },
]
